spring:
  datasource:

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.129.220.209:3306/mjmherp?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: mjmh
    password: mjmhtest2017
  jpa:
    hibernate:
      ddl-auto: update #ddl-auto:设为create表示每次都重新建表
    show-sql: true
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
